export { default as Grey } from "./grey.png";
export { default as Horse } from "./horse.png";
export { default as Snooker } from "./snooker.png";
export { default as Kabaddi } from "./kabaddi.png";
export { default as TableT } from "./tableT.png";
export { default as Volley } from "./volley.png";
export { default as Esoc } from "./esoccer.png";
export { default as Badmin } from "./badminotn.png";
export { default as amfootball } from "./americanF.png";