export function GameData() {
  const dataList = [
    {
      title: "bookmaker1",
      countRow: 6,

      data: [
        {
          selectionId: 1,
          RunnerName: "South Africa",
          sortPriority: 1,
          handicap: null,
          status: "SUSPENDED",
          lastPriceTraded: 0,
          totalMatched: 0,
          ex: {
            availableToBack: [
              {
                price: "0",
                size: "0",
              },
              {
                price: "0",
                size: "0",
              },
              {
                price: "0",
                size: "0",
              },
            ],
            availableToLay: [
              {
                price: "0",
                size: "0",
              },
              {
                price: "0",
                size: "0",
              },
              {
                price: "0",
                size: "0",
              },
            ],
            tradedVolume: null,
          },
        },
        {
          selectionId: 2,
          RunnerName: "Australia",
          sortPriority: 2,
          handicap: null,
          status: "ACTIVE",
          lastPriceTraded: 0,
          totalMatched: 0,
          ex: {
            availableToBack: [
              {
                price: "16",
                size: "1000000",
              },
              {
                price: "0",
                size: "0",
              },
              {
                price: "0",
                size: "0",
              },
            ],
            availableToLay: [
              {
                price: "17.5",
                size: "1000000",
              },
              {
                price: "0",
                size: "0",
              },
              {
                price: "0",
                size: "0",
              },
            ],
            tradedVolume: null,
          },
        },
      ],
    },
    {
      title: "bookmaker2",
      countRow: 2,
      data: [
        {
          selectionId: 1,
          RunnerName: "South Africa",
          sortPriority: 1,
          handicap: null,
          status: "SUSPENDED",
          lastPriceTraded: 0,
          totalMatched: 0,
          ex: {
            availableToBack: [
              {
                price: "0",
                size: "0",
              },
            ],
            availableToLay: [
              {
                price: "0",
                size: "0",
              },
            ],
            tradedVolume: null,
          },
        },
        {
          selectionId: 2,
          RunnerName: "Australia",
          sortPriority: 2,
          handicap: null,
          status: "ACTIVE",
          lastPriceTraded: 0,
          totalMatched: 0,
          ex: {
            availableToBack: [
              {
                price: "16",
                size: "1000000",
              },
            ],
            availableToLay: [
              {
                price: "17.5",
                size: "1000000",
              },
            ],
            tradedVolume: null,
          },
        },
      ],
    },
  ];
  return dataList;
}

export function SessionMarketData() {
  const sessionMarketDataList = [
    {
      title: "Session market",
      data: [
        {
          SelectionId: "20overrunsa",
          RunnerName: "20 over run SA",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 500000,
        },
        {
          SelectionId: "20overrunsa2",
          RunnerName: "20 over run SA 2",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "Ball Running",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 100000,
        },
        {
          SelectionId: "20overrunbhavsa2",
          RunnerName: "20 over run bhav SA 2",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 25000,
        },
        {
          SelectionId: "14_3overrunsa",
          RunnerName: "14.3 over run SA",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "15overrunsa",
          RunnerName: "15 over run SA",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "16overrunsa",
          RunnerName: "16 over run SA",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "50overrunssasavsausadv",
          RunnerName: "50 over runs SA(SA vs AUS)adv",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 300000,
        },
        {
          SelectionId: "50overrunsa2",
          RunnerName: "50 over run SA 2",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "Ball Running",
          FinalStatus: null,
          isActive: false,
          min: 10,
          max: 100000,
        },
        {
          SelectionId: "50overrunbhavsa",
          RunnerName: "50 over run bhav SA",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "50overrunbhavsa2",
          RunnerName: "50 over run bhav SA 2",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "Ball Running",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "fallof5thwktsa",
          RunnerName: "Fall of 5th wkt SA",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 300000,
        },
        {
          SelectionId: "fallof5thwktrunbhavsa",
          RunnerName: "Fall of 5th wkt run bhav SA",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 700000,
        },
        {
          SelectionId: "fallof5thwktrunbhavsa2",
          RunnerName: "Fall of 5th wkt run bhav SA 2",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 300000,
        },
        {
          SelectionId: "hklaasenrun",
          RunnerName: "H Klaasen run",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 300000,
        },
        {
          SelectionId: "dmillerrun",
          RunnerName: "D Miller run",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 300000,
        },
        {
          SelectionId: "hklaasenrunbhav",
          RunnerName: "H Klaasen run bhav",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "Ball Running",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 700000,
        },
        {
          SelectionId: "hklaasenrunbhav2",
          RunnerName: "H Klaasen run bhav 2",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 300000,
        },
        {
          SelectionId: "dmillerrunbhav",
          RunnerName: "D Miller run bhav",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 700000,
        },
        {
          SelectionId: "dmillerrunbhav2",
          RunnerName: "D Miller run bhav 2",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 300000,
        },
        {
          SelectionId: "5thwktpshipboundariessa",
          RunnerName: "5th wkt pship boundaries SA",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "Ball Running",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 50000,
        },
        {
          SelectionId: "hklaasenboundaries",
          RunnerName: "H Klaasen boundaries",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 50000,
        },
        {
          SelectionId: "dmillerboundaries",
          RunnerName: "D Miller boundaries",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 50000,
        },
        {
          SelectionId: "5thwktlosttosaballs",
          RunnerName: "5th wkt lost to SA balls",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "Ball Running",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 50000,
        },
        {
          SelectionId: "howmanyballsfacebyhklaasen",
          RunnerName: "How many balls face by H Klaasen",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 50000,
        },
        {
          SelectionId: "howmanyballsfacebydmiller",
          RunnerName: "How many balls face by D Miller",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "Ball Running",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 50000,
        },
        {
          SelectionId: "14_1ballrunsa",
          RunnerName: "14.1 ball run SA",
          mktype: null,
          type: "Ball By Ball",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "14_2ballrunsa",
          RunnerName: "14.2 ball run SA",
          mktype: null,
          type: "Ball By Ball",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "14_3ballrunsa",
          RunnerName: "14.3 ball run SA",
          mktype: null,
          type: "Ball By Ball",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "14_4ballrunsa",
          RunnerName: "14.4 ball run SA",
          mktype: null,
          type: "Ball By Ball",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "14_5ballrunsa",
          RunnerName: "14.5 ball run SA",
          mktype: null,
          type: "Ball By Ball",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "14_6ballrunsa",
          RunnerName: "14.6 ball run SA",
          mktype: null,
          type: "Ball By Ball",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
      ],
    },
    {
      title: "Fancy market",
      data: [
        {
          SelectionId: "20overrunsa",
          RunnerName: "20 over run SA",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 500000,
        },
        {
          SelectionId: "20overrunsa2",
          RunnerName: "20 over run SA 2",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "Ball Running",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 100000,
        },
        {
          SelectionId: "20overrunbhavsa2",
          RunnerName: "20 over run bhav SA 2",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 25000,
        },
        {
          SelectionId: "14_3overrunsa",
          RunnerName: "14.3 over run SA",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "15overrunsa",
          RunnerName: "15 over run SA",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "16overrunsa",
          RunnerName: "16 over run SA",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "50overrunssasavsausadv",
          RunnerName: "50 over runs SA(SA vs AUS)adv",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 300000,
        },
        {
          SelectionId: "50overrunsa2",
          RunnerName: "50 over run SA 2",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "Ball Running",
          FinalStatus: null,
          isActive: false,
          min: 10,
          max: 100000,
        },
        {
          SelectionId: "50overrunbhavsa",
          RunnerName: "50 over run bhav SA",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "50overrunbhavsa2",
          RunnerName: "50 over run bhav SA 2",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "Ball Running",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "fallof5thwktsa",
          RunnerName: "Fall of 5th wkt SA",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 300000,
        },
        {
          SelectionId: "fallof5thwktrunbhavsa",
          RunnerName: "Fall of 5th wkt run bhav SA",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 700000,
        },
        {
          SelectionId: "fallof5thwktrunbhavsa2",
          RunnerName: "Fall of 5th wkt run bhav SA 2",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 300000,
        },
        {
          SelectionId: "hklaasenrun",
          RunnerName: "H Klaasen run",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 300000,
        },
        {
          SelectionId: "dmillerrun",
          RunnerName: "D Miller run",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 300000,
        },
        {
          SelectionId: "hklaasenrunbhav",
          RunnerName: "H Klaasen run bhav",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "Ball Running",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 700000,
        },
        {
          SelectionId: "hklaasenrunbhav2",
          RunnerName: "H Klaasen run bhav 2",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 300000,
        },
        {
          SelectionId: "dmillerrunbhav",
          RunnerName: "D Miller run bhav",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 700000,
        },
        {
          SelectionId: "dmillerrunbhav2",
          RunnerName: "D Miller run bhav 2",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 300000,
        },
        {
          SelectionId: "5thwktpshipboundariessa",
          RunnerName: "5th wkt pship boundaries SA",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "Ball Running",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 50000,
        },
        {
          SelectionId: "hklaasenboundaries",
          RunnerName: "H Klaasen boundaries",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 50000,
        },
        {
          SelectionId: "dmillerboundaries",
          RunnerName: "D Miller boundaries",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 50000,
        },
        {
          SelectionId: "5thwktlosttosaballs",
          RunnerName: "5th wkt lost to SA balls",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "Ball Running",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 50000,
        },
        {
          SelectionId: "howmanyballsfacebyhklaasen",
          RunnerName: "How many balls face by H Klaasen",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 50000,
        },
        {
          SelectionId: "howmanyballsfacebydmiller",
          RunnerName: "How many balls face by D Miller",
          mktype: null,
          type: "Normal",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "Ball Running",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 50000,
        },
        {
          SelectionId: "14_1ballrunsa",
          RunnerName: "14.1 ball run SA",
          mktype: null,
          type: "Ball By Ball",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "14_2ballrunsa",
          RunnerName: "14.2 ball run SA",
          mktype: null,
          type: "Ball By Ball",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "14_3ballrunsa",
          RunnerName: "14.3 ball run SA",
          mktype: null,
          type: "Ball By Ball",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "14_4ballrunsa",
          RunnerName: "14.4 ball run SA",
          mktype: null,
          type: "Ball By Ball",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "14_5ballrunsa",
          RunnerName: "14.5 ball run SA",
          mktype: null,
          type: "Ball By Ball",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
        {
          SelectionId: "14_6ballrunsa",
          RunnerName: "14.6 ball run SA",
          mktype: null,
          type: "Ball By Ball",
          LayPrice1: "0",
          LaySize1: "0",
          BackPrice1: "0",
          BackSize1: "0",
          GameStatus: "SUSPENDED",
          FinalStatus: null,
          isActive: false,
          min: 100,
          max: 200000,
        },
      ],
    },
  ];

  return sessionMarketDataList;
}

export function MatchOdds() {
  return [
    {
      marketId: "1.221131127",
      isMarketDataDelayed: false,
      status: "OPEN",
      betDelay: 5,
      bspReconciled: false,
      complete: true,
      inplay: true,
      numberOfWinners: 1,
      numberOfRunners: 2,
      numberOfActiveRunners: 2,
      lastMatchTime: "2023-11-16T09:50:07.509Z",
      totalMatched: 25850689.47,
      totalAvailable: 8026072.86,
      crossMatching: true,
      runnersVoidable: false,
      version: 5586725478,
      title: "Match Odds",
      runners: [
        {
          selectionId: 349,
          handicap: 0,
          status: "ACTIVE",
          lastPriceTraded: 6.8,
          totalMatched: 1194427.54,
          RunnerName:"SA Test",
          ex: {
            availableToBack: [
              {
                price: 6.8,
                size: 9975.49,
              },
              {
                price: 6.6,
                size: 1092.47,
              },
              {
                price: 6.4,
                size: 19106.09,
              },
            ],
            availableToLay: [
              {
                price: 7,
                size: 31.2,
              },
              {
                price: 7.2,
                size: 631.32,
              },
              {
                price: 7.4,
                size: 28487.91,
              },
            ],
            tradedVolume: [],
          },
        },
        {
          selectionId: 16606,
          handicap: 0,
          status: "ACTIVE",
          lastPriceTraded: 1.17,
          totalMatched: 24656261.93,
          RunnerName:"India Test",
          ex: {
            availableToBack: [
              {
                price: 1.16,
                size: 184191.78,
              },
              {
                price: 1.15,
                size: 89559.16,
              },
              {
                price: 1.14,
                size: 53258.96,
              },
            ],
            availableToLay: [
              {
                price: 1.17,
                size: 50362.01,
              },
              {
                price: 1.18,
                size: 114022.24,
              },
              {
                price: 1.19,
                size: 86297.61,
              },
            ],
            tradedVolume: [],
          },
        },
      ],
      lastUpdatedTime: 1700128208,
    },
  ];
}
